# Modeling / Architecture

This phase builds the first collaborative recommendation model.

## Objective

Use historical user-item ratings to learn personalized product
preference scores, which will later be used to rank candidate products.

## Model

Explicit Matrix Factorization implemented in PyTorch.

Ratings are centered around 3 stars:

- 1 → -1.0
- 2 → -0.5
- 3 → 0.0
- 4 → +0.5
- 5 → +1.0

The model learns separate latent representations for users and products.

## Important cold-start limitation

The collaborative model only learns item representations for products
with interactions in the training period (≤ 2021).

Products with zero training interactions remain in the global catalog
but cannot receive a collaborative score. This limitation is intentional
and will later be addressed using content-based representations.

In [2]:
from pathlib import Path

import duckdb
import pandas as pd
import numpy as np


PROJECT_ROOT = Path.cwd().parent

INTERACTION_PATH = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "electronics_interactions"
    / "*.parquet"
)

OUTPUT_DIR = PROJECT_ROOT / "data" / "processed"

con = duckdb.connect()

In [3]:
users = con.sql(f"""
    SELECT DISTINCT user_id
    FROM read_parquet('{INTERACTION_PATH}')
    WHERE timestamp < 1640995200000
    ORDER BY user_id
""").df()

users["user_idx"] = np.arange(
    len(users),
    dtype=np.int32,
)

users = users[["user_idx", "user_id"]]

print(f"Training users: {len(users):,}")
users.head()

Training users: 16,058,864

   user_idx                       user_id
0         0  AE2222C2STTMXNUHXTVDF55R7E3Q
1         1  AE2222FRPDMNOMYOMCWIANTXP7UQ
2         2  AE2222VGHFD37G7NOCWXASYY3ZDQ
3         3  AE2222WEGI5MUXLFZW6UKKUSI74A
4         4  AE22232OB6S7UAC75JUFYRGBSHIQ

In [4]:
mf_items = con.sql(f"""
    SELECT DISTINCT parent_asin
    FROM read_parquet('{INTERACTION_PATH}')
    WHERE timestamp < 1640995200000
    ORDER BY parent_asin
""").df()

mf_items["mf_item_idx"] = np.arange(
    len(mf_items),
    dtype=np.int32,
)

mf_items = mf_items[["mf_item_idx", "parent_asin"]]

print(f"Training items: {len(mf_items):,}")
mf_items.head()

Training items: 1,395,130

   mf_item_idx parent_asin
0            0  0007182147
1            1  0011300000
2            2  0060009810
3            3  0060219602
4            4  0060897082

In [5]:
users.to_parquet(
    OUTPUT_DIR / "mf_users.parquet",
    index=False,
)

mf_items.to_parquet(
    OUTPUT_DIR / "mf_items.parquet",
    index=False,
)

In [5]:
assert users["user_idx"].is_unique
assert users["user_id"].is_unique

assert mf_items["mf_item_idx"].is_unique
assert mf_items["parent_asin"].is_unique

assert users["user_idx"].iloc[0] == 0
assert mf_items["mf_item_idx"].iloc[0] == 0

print("MF index mappings validated.")

MF index mappings validated.

In [6]:
rating_to_target = {
    1.0: -1.0,
    2.0: -0.5,
    3.0: 0.0,
    4.0: 0.5,
    5.0: 1.0,
}

In [7]:
train_interactions = con.sql(f"""
    SELECT
        u.user_idx,
        i.mf_item_idx,
        CASE rating
            WHEN 1.0 THEN -1.0
            WHEN 2.0 THEN -0.5
            WHEN 3.0 THEN  0.0
            WHEN 4.0 THEN  0.5
            WHEN 5.0 THEN  1.0
        END AS target
    FROM read_parquet('{INTERACTION_PATH}') r
    INNER JOIN users u
        ON r.user_id = u.user_id
    INNER JOIN mf_items i
        ON r.parent_asin = i.parent_asin
    WHERE EXTRACT(
        YEAR FROM to_timestamp(r.timestamp / 1000)
    ) <= 2021
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

In [8]:
print(train_interactions.shape)
print(train_interactions.head())
print(train_interactions.dtypes)
print(train_interactions["target"].value_counts().sort_index())

(37006469, 3)
   user_idx  mf_item_idx  target
0   1331200       850425     1.0
1   1331201      1378706     1.0
2   1331202      1378937     1.0
3   1331203      1263620     1.0
4   1331204       561793     1.0
user_idx         int32
mf_item_idx      int32
target         float64
dtype: object
target
-1.0     4285643
-0.5     1864074
 0.0     2419023
 0.5     4840173
 1.0    23597556
Name: count, dtype: int64

### Preparing data

In [9]:
import torch
from torch.utils.data import Dataset, DataLoader

user_indices = train_interactions["user_idx"].to_numpy(dtype=np.int64)
item_indices = train_interactions["mf_item_idx"].to_numpy(dtype=np.int64)
targets = train_interactions["target"].to_numpy(dtype=np.float32)

print(user_indices.nbytes / 1024**2, "MB")
print(item_indices.nbytes / 1024**2, "MB")
print(targets.nbytes / 1024**2, "MB")

282.33695220947266 MB
282.33695220947266 MB
141.16847610473633 MB

### MF Dataset

In [12]:
class MFDataset(Dataset):
    def __init__(self, user_indices, item_indices, targets):
        self.user_indices = user_indices
        self.item_indices = item_indices
        self.targets = targets

    def __len__(self):
        return len(self.targets)

    def __getitem__(self, idx):
        return (
            self.user_indices[idx],
            self.item_indices[idx],
            self.targets[idx],
        )

In [13]:
train_dataset = MFDataset(
    user_indices,
    item_indices,
    targets,
)

print("Training examples:", len(train_dataset))
print("First example:", train_dataset[0])

Training examples: 37006469
First example: (np.int64(102400), np.int64(1388149), np.float32(1.0))

### MF Model

In [14]:
import torch
import torch.nn as nn


LATENT_DIM = 16


class MatrixFactorization(nn.Module):
    def __init__(self, num_users, num_items, latent_dim=LATENT_DIM):
        super().__init__()

        self.user_embeddings = nn.Embedding(
            num_users,
            latent_dim,
            sparse=True,
        )

        self.item_embeddings = nn.Embedding(
            num_items,
            latent_dim,
            sparse=True,
        )

        self.user_bias = nn.Embedding(
            num_users,
            1,
            sparse=True,
        )

        self.item_bias = nn.Embedding(
            num_items,
            1,
            sparse=True,
        )

        self.global_bias = nn.Parameter(
            torch.tensor(0.0)
        )

    def forward(self, user_idx, item_idx):
        user_vec = self.user_embeddings(user_idx)
        item_vec = self.item_embeddings(item_idx)

        interaction = (user_vec * item_vec).sum(dim=1)

        user_bias = self.user_bias(user_idx).squeeze(-1)
        item_bias = self.item_bias(item_idx).squeeze(-1)

        return (
            interaction
            + user_bias
            + item_bias
            + self.global_bias
        )

In [15]:
num_users = len(users)
num_items = len(mf_items)

print("Users:", num_users)
print("Items:", num_items)
print("Latent dimensions:", LATENT_DIM)

Users: 16058864
Items: 1395130
Latent dimensions: 16

In [16]:
model = MatrixFactorization(
    num_users=num_users,
    num_items=num_items,
    latent_dim=LATENT_DIM,
)

print(model)

MatrixFactorization(
  (user_embeddings): Embedding(16058864, 16, sparse=True)
  (item_embeddings): Embedding(1395130, 16, sparse=True)
  (user_bias): Embedding(16058864, 1, sparse=True)
  (item_bias): Embedding(1395130, 1, sparse=True)
)

In [18]:
sum(p.numel() for p in model.parameters())

296717899

In [19]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    props = torch.cuda.get_device_properties(0)

    print("GPU:", props.name)
    print("Total GPU memory:",
          round(props.total_memory / 1024**3, 2), "GB")

    print("Currently allocated:",
          round(torch.cuda.memory_allocated() / 1024**3, 2), "GB")

    print("Currently reserved:",
          round(torch.cuda.memory_reserved() / 1024**3, 2), "GB")

CUDA available: True
GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
Total GPU memory: 3.68 GB
Currently allocated: 0.0 GB
Currently reserved: 0.0 GB

### CPU training test

In [20]:
device = torch.device("cpu")
model = model.to(device)

print("Model device:", model.user_embeddings.weight.device)

Model device: cpu

In [21]:
batch_size = 1024

test_users = torch.randint(
    0,
    num_users,
    (batch_size,),
    dtype=torch.long,
)

test_items = torch.randint(
    0,
    num_items,
    (batch_size,),
    dtype=torch.long,
)

test_targets = torch.randn(batch_size)

In [22]:
predictions = model(test_users, test_items)

loss = nn.functional.mse_loss(
    predictions,
    test_targets,
)

loss.backward()

print("Prediction shape:", predictions.shape)
print("Loss:", loss.item())
print("Forward/backward test: successful")

Prediction shape: torch.Size([1024])
Loss: 18.205202102661133
Forward/backward test: successful

### Sanity check for CPU training complete

In [17]:
sparse_parameters = [
    model.user_embeddings.weight,
    model.item_embeddings.weight,
    model.user_bias.weight,
    model.item_bias.weight,
]

optimizer = torch.optim.SGD(
    model.parameters(),
    lr=0.01,
)

In [18]:
print(type(optimizer).__name__)

SGD

### Training one real batch

In [20]:
import duckdb

TRAINING_PATH = (
    PROJECT_ROOT / "data" / "processed" / "mf_training" / "*.parquet"
)

con = duckdb.connect()

batch_df = con.execute(f"""
    SELECT
        user_idx,
        mf_item_idx,
        target
    FROM read_parquet('{TRAINING_PATH}')
    LIMIT 1024
""").fetchdf()

con.close()

print(batch_df.shape)
print(batch_df.head())

(1024, 3)
   user_idx  mf_item_idx  target
0  15728703       114907     0.0
1  15728740       665371     1.0
2  15728842      1394026     1.0
3  15729049       812987    -1.0
4  15729074       637996    -1.0

In [21]:
batch_users = torch.tensor(
    batch_df["user_idx"].to_numpy(),
    dtype=torch.long,
)

batch_items = torch.tensor(
    batch_df["mf_item_idx"].to_numpy(),
    dtype=torch.long,
)

batch_targets = torch.tensor(
    batch_df["target"].to_numpy(),
    dtype=torch.float32,
)

In [22]:
print("Users:", batch_users.shape)
print("Items:", batch_items.shape)
print("Targets:", batch_targets.shape)

print("User index range:",
      batch_users.min().item(),
      batch_users.max().item())

print("Item index range:",
      batch_items.min().item(),
      batch_items.max().item())

Users: torch.Size([1024])
Items: torch.Size([1024])
Targets: torch.Size([1024])
User index range: 15728703 15804303
Item index range: 232 1394220

In [23]:
model.train()

optimizer.zero_grad()

predictions = model(
    batch_users,
    batch_items,
)

loss = nn.functional.mse_loss(
    predictions,
    batch_targets,
)

loss.backward()

optimizer.step()

print("Training step successful")
print("Loss:", loss.item())

Training step successful
Loss: 18.34758186340332

### MF optimization

- Tested SparseAdam with the 16-dimensional MF architecture.
- The first real optimization step caused a kernel crash under the available
  14 GB system RAM, indicating excessive optimizer-state memory.
- Switched to SGD, which successfully completed a real sparse-embedding
  optimization step.
- Chose SGD for the first baseline to minimize optimizer memory and establish
  a reliable training configuration before considering more sophisticated
  optimizers.

## Validation Evaluation
### 2022 Ground Truth

In [1]:
import duckdb

TRAINING_DIR = "data/processed/electronics_interactions"

con = duckdb.connect()

con.execute("""
    SELECT
        COUNT(*) AS interactions_2022,
        COUNT(DISTINCT user_id) AS users_2022,
        COUNT(DISTINCT parent_asin) AS items_2022
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
    WHERE timestamp >= 1640995200000
      AND timestamp < 1672531200000
""").df()

   interactions_2022  users_2022  items_2022
0            4471117     3085677      392567

In [2]:
con.execute("""
    SELECT
        typeof(timestamp) AS timestamp_type,
        MIN(timestamp) AS min_timestamp,
        MAX(timestamp) AS max_timestamp,
        COUNT(*) AS total_rows
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
    GROUP BY typeof(timestamp)
""").df()

  timestamp_type  min_timestamp  max_timestamp  total_rows
0         BIGINT   848336280000  1694625981867    43365426

In [3]:
con.execute("""
    SELECT timestamp
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
    LIMIT 10
""").df()

       timestamp
0  1523093017534
1  1592678549731
2  1658185117948
3  1290278495000
4  1676601581238
5  1344406083000
6  1384912340000
7  1408995743000
8  1439226089000
9  1456772365000

In [4]:
validation_stats = con.execute("""
    SELECT
        COUNT(*) AS positive_interactions_2022,
        COUNT(DISTINCT user_id) AS evaluation_users,
        COUNT(DISTINCT parent_asin) AS relevant_items
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
    WHERE timestamp >= 1640995200000
      AND timestamp < 1672531200000
      AND rating >= 4
""").df()

validation_stats

   positive_interactions_2022  evaluation_users  relevant_items
0                     3182966           2203571          322133

In [5]:
training_item_cohorts = con.execute("""
    WITH training_item_counts AS (
        SELECT
            parent_asin,
            COUNT(*) AS training_interactions
        FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
        WHERE timestamp < 1640995200000
        GROUP BY parent_asin
    )

    SELECT
        CASE
            WHEN training_interactions IS NULL THEN 'true_cold'
            WHEN training_interactions BETWEEN 1 AND 5 THEN 'low'
            WHEN training_interactions BETWEEN 6 AND 20 THEN 'medium'
            ELSE 'warm'
        END AS cohort,
        COUNT(*) AS items
    FROM (
        SELECT
            c.parent_asin,
            t.training_interactions
        FROM (
            SELECT DISTINCT parent_asin
            FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
            WHERE timestamp >= 1640995200000
              AND timestamp < 1672531200000
              AND rating >= 4
        ) c
        LEFT JOIN training_item_counts t
            ON c.parent_asin = t.parent_asin
    )
    GROUP BY cohort
    ORDER BY
        CASE cohort
            WHEN 'true_cold' THEN 1
            WHEN 'low' THEN 2
            WHEN 'medium' THEN 3
            WHEN 'warm' THEN 4
        END
""").df()

training_item_cohorts

      cohort   items
0  true_cold  118943
1        low   66559
2     medium   53412
3       warm   83219

In [6]:
duplicate_check = con.execute("""
    SELECT
        COUNT(*) AS positive_rows,
        COUNT(DISTINCT user_id || '|' || parent_asin) AS unique_user_item_pairs
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
    WHERE timestamp >= 1640995200000
      AND timestamp < 1672531200000
      AND rating >= 4
""").df()

duplicate_check

   positive_rows  unique_user_item_pairs
0        3182966                 3182966

In [7]:
validation_ground_truth_path = "../data/processed/mf_validation_ground_truth.parquet"

con.execute(f"""
    COPY (
        SELECT
            user_id,
            parent_asin AS item_id,
            CASE
                WHEN training_interactions IS NULL THEN 'true_cold'
                WHEN training_interactions BETWEEN 1 AND 5 THEN 'low'
                WHEN training_interactions BETWEEN 6 AND 20 THEN 'medium'
                ELSE 'warm'
            END AS item_cohort
        FROM (
            SELECT
                v.user_id,
                v.parent_asin,
                t.training_interactions
            FROM (
                SELECT
                    user_id,
                    parent_asin
                FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
                WHERE timestamp >= 1640995200000
                  AND timestamp < 1672531200000
                  AND rating >= 4
            ) v
            LEFT JOIN (
                SELECT
                    parent_asin,
                    COUNT(*) AS training_interactions
                FROM read_parquet('../data/processed/electronics_interactions/*.parquet')
                WHERE timestamp < 1640995200000
                GROUP BY parent_asin
            ) t
            ON v.parent_asin = t.parent_asin
        )
    ) TO '{validation_ground_truth_path}'
    (FORMAT PARQUET)
""")

In [8]:
con.execute(f"""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT user_id) AS users,
        COUNT(DISTINCT item_id) AS items
    FROM read_parquet('{validation_ground_truth_path}')
""").df()

      rows    users   items
0  3182966  2203571  322133

In [9]:
from pathlib import Path
import pandas as pd

catalog_path = Path("../data/processed/product_catalog.parquet")

catalog = pd.read_parquet(
    catalog_path,
    columns=["parent_asin", "item_idx"]
)

print("Catalog rows:", len(catalog))
print("Item index min:", catalog["item_idx"].min())
print("Item index max:", catalog["item_idx"].max())
print("Unique ASINs:", catalog["parent_asin"].nunique())
print("Unique indices:", catalog["item_idx"].nunique())

Catalog rows: 1609860
Item index min: 0
Item index max: 1609859
Unique ASINs: 1609860
Unique indices: 1609860

In [10]:
mf_training_path = "../data/processed/mf_training"

con.execute(f"""
    SELECT
        MIN(mf_item_idx) AS min_mf_item_idx,
        MAX(mf_item_idx) AS max_mf_item_idx,
        COUNT(DISTINCT mf_item_idx) AS unique_mf_items,
        COUNT(*) AS training_rows
    FROM read_parquet('{mf_training_path}/*.parquet')
""").df()

   min_mf_item_idx  max_mf_item_idx  unique_mf_items  training_rows
0                0          1395129          1395130       37011296

In [11]:
mf_items = con.execute("""
    SELECT *
    FROM read_parquet('../data/processed/mf_items.parquet')
    LIMIT 10
""").df()

mf_items

   mf_item_idx parent_asin
0            0  0007182147
1            1  0011300000
2            2  0060009810
3            3  0060219602
4            4  0060897082
5            5  0060959274
6            6  0060984368
7            7  0062970704
8            8  0070524076
9            9  0071341196

In [12]:
con.execute("""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT parent_asin) AS unique_items,
        MIN(mf_item_idx) AS min_idx,
        MAX(mf_item_idx) AS max_idx,
        COUNT(DISTINCT mf_item_idx) AS unique_indices
    FROM read_parquet('../data/processed/mf_items.parquet')
""").df()

      rows  unique_items  min_idx  max_idx  unique_indices
0  1395130       1395130        0  1395129         1395130

In [13]:
import json
import torch
import torch.nn as nn
from pathlib import Path

In [14]:
class MatrixFactorization(nn.Module):
    def __init__(self, num_users, num_items, latent_dim=16):
        super().__init__()

        self.user_embeddings = nn.Embedding(
            num_users,
            latent_dim,
            sparse=True,
        )

        self.item_embeddings = nn.Embedding(
            num_items,
            latent_dim,
            sparse=True,
        )

        self.user_bias = nn.Embedding(
            num_users,
            1,
            sparse=True,
        )

        self.item_bias = nn.Embedding(
            num_items,
            1,
            sparse=True,
        )

        self.global_bias = nn.Parameter(torch.tensor(0.0))

    def forward(self, user_idx, item_idx):
        user_vec = self.user_embeddings(user_idx)
        item_vec = self.item_embeddings(item_idx)

        interaction = (user_vec * item_vec).sum(dim=1)

        user_bias = self.user_bias(user_idx).squeeze(-1)
        item_bias = self.item_bias(item_idx).squeeze(-1)

        return (
            interaction
            + user_bias
            + item_bias
            + self.global_bias
        )

In [15]:
config_path = Path("../models/mf_3epoch_config.json")

with open(config_path) as f:
    config = json.load(f)

config

{'num_users': 16058864,
 'num_items': 1395130,
 'latent_dim': 16,
 'batch_size': 1024,
 'learning_rate': 0.01,
 'epochs': 3,
 'random_seed': 42,
 'rating_mapping': {'1': -1.0, '2': -0.5, '3': 0.0, '4': 0.5, '5': 1.0}}

In [16]:
model = MatrixFactorization(
    num_users=config["num_users"],
    num_items=config["num_items"],
    latent_dim=config["latent_dim"],
)

In [17]:
model_path = Path("../models/mf_3epoch.pt")

state_dict = torch.load(
    model_path,
    map_location="cpu",
)

model.load_state_dict(state_dict)

model.eval()

MatrixFactorization(
  (user_embeddings): Embedding(16058864, 16, sparse=True)
  (item_embeddings): Embedding(1395130, 16, sparse=True)
  (user_bias): Embedding(16058864, 1, sparse=True)
  (item_bias): Embedding(1395130, 1, sparse=True)
)

### Top-K Scoring

In [18]:
validation_users = con.execute("""
    SELECT DISTINCT user_id
    FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet')
    LIMIT 32
""").df()

validation_users.head()

                        user_id
0  AEBEBINMQBVT45WWNQWJ37J7MZEQ
1  AE6UUUBRJ7KZ3RR55OFJ7WKTVNGA
2  AGUWXYYUSGJ3PRQ3DOPYPK2JZH2A
3  AG6TJ4FC2VS5WRQPRDWBTHCID65Q
4  AG6BEOVL7CXFLR42XV3FBNFVCEFQ

In [19]:
eval_users = con.execute("""
    SELECT
        g.user_id,
        u.user_idx
    FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet') AS g
    INNER JOIN read_parquet('../data/processed/mf_users.parquet') AS u
        ON g.user_id = u.user_id
    GROUP BY g.user_id, u.user_idx
    LIMIT 32
""").df()

eval_users

                         user_id  user_idx
0   AHXG5OJ6YEFCM44FTZ22DJBNBP2A  15729245
1   AHXG6A4KGCSCNRZL5T2XXHLTIVGA  15729316
2   AHXG7BWB2232VY3ECNGDIKTWU6NA  15729427
3   AHXGBGNL5XIQR7TXGET6FR6B6Z3Q  15729666
4   AHXGFEAT542Y5S3OQHY43RBJP4QA  15730153
5   AHXGFGX6BFFZZQQTKBW3UEHWKS5Q  15730164
6   AHXGGCJX4LTIE57L7TISA5M7QM7A  15730293
7   AHXGGSONLOKPOC42S4ZLTSIHNRDQ  15730364
8   AHXGIS276EOAWLIESEUYRJ3Z4FEQ  15730588
9   AHXGM5T2LUNQYEEVTJC37RRS6J5A  15731017
10  AHXGMQGMO5KPUHG3ADXWA2GOYS2Q  15731092
11  AHXGRBY2YLA7YFREIJ2QL5KJ35VA  15731649
12  AHXGRDTYYCLNVM2FJZX7JXNYCB3A  15731659
13  AHXGROQWH4PBW2RUFMA6CSU3TZFQ  15731699
14  AHXGURSMJ75N2IFVWIKOGHAO6HLA  15732078
15  AHXGWQUG3RCHCIB2HU5VNRHI233A  15732305
16  AHXGXUX6C55M3WUMYOIADSIHTWKQ  15732445
17  AHXH5A7CWZOIT6I6MIIGWY73G7IQ  15733085
18  AHXH64XNHOMUNJAF2TIQPF3U3ZJA  15733213
19  AHXH73IX5II7DKLLZTRAV2CQQVAA  15733339
20  AHXHA4JL6QHK77UVKEZEPZAVJACQ  15733459
21  AHXHAFBD4J7KXSOOBORI22O45L4Q  15733498
22  AHXHCPB2F2F63555SET2ZKV4X7JQ  15733737
23  AHXHDT7VPVC5TUTOH4T2OO44FVPQ  15733856
24  AHXHEAXGFTGSRHAV54AEQ7LCGJTA  15733915
25  AHXHGDID6V3P36IFMGLM2NN6WQAA  15734148
26  AHXHHZXX6WVBTPBNQM2TLPWQUZNA  15734358
27  AHXHIBWMQMOIGMDXS55EN3BERMQA  15734391
28  AHXHIYY4OZOL63MCBEU5E4H32LSQ  15734490
29  AHXHJE3SQKZ7JI2D64KSF64OTIYQ  15734537
30  AHXHLWKB62AORTX5TFVAQOD7L3BQ  15734878
31  AHXHMD3UWLJ4YH4RSRARXD5YVBBQ  15734935

In [20]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = model.to(device)

print("Using:", device)

Using: cuda

In [21]:
user_indices = torch.tensor(
    eval_users["user_idx"].to_numpy(),
    dtype=torch.long,
    device=device,
)

with torch.no_grad():
    user_vectors = model.user_embeddings(user_indices)
    user_biases = model.user_bias(user_indices).squeeze(-1)

    item_vectors = model.item_embeddings.weight
    item_biases = model.item_bias.weight.squeeze(-1)

    scores = (
        user_vectors @ item_vectors.T
        + user_biases[:, None]
        + item_biases[None, :]
        + model.global_bias
    )

print("Score matrix shape:", scores.shape)

Score matrix shape: torch.Size([32, 1395130])

In [39]:
seen_items = con.execute("""
    SELECT DISTINCT
        r.user_id,
        i.mf_item_idx
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet') AS r
    INNER JOIN read_parquet('../data/processed/mf_users.parquet') AS u
        ON r.user_id = u.user_id
    INNER JOIN read_parquet('../data/processed/mf_items.parquet') AS i
        ON r.parent_asin = i.parent_asin
    INNER JOIN eval_users_sample AS e
        ON r.user_id = e.user_id
    WHERE r.timestamp < 1640995200000
""").df()

In [40]:
user_to_row = {
    user_id: row
    for row, user_id in enumerate(eval_users["user_id"])
}

for _, row in seen_items.iterrows():
    user_id = row["user_id"]
    item_idx = int(row["mf_item_idx"])

    if user_id in user_to_row:
        scores[user_to_row[user_id], item_idx] = float("-inf")

### Top-K recommendations

In [41]:
top5_scores, top5_indices = torch.topk(scores, k=5, dim=1)
top10_scores, top10_indices = torch.topk(scores, k=10, dim=1)

print("Top-5 shape:", top5_indices.shape)
print("Top-10 shape:", top10_indices.shape)

Top-5 shape: torch.Size([32, 5])
Top-10 shape: torch.Size([32, 10])

In [42]:
recommended_items = top10_indices.cpu().numpy()

seen_by_user = {
    user_id: set(group["mf_item_idx"].astype(int))
    for user_id, group in seen_items.groupby("user_id")
}

violations = []

for row_idx, user_id in enumerate(eval_users["user_id"]):
    recommended = set(recommended_items[row_idx])

    already_seen = recommended.intersection(
        seen_by_user.get(user_id, set())
    )

    if already_seen:
        violations.append(
            {
                "user_id": user_id,
                "seen_recommended_items": already_seen,
            }
        )

print("Users with seen-item violations:", len(violations))

Users with seen-item violations: 0

### Checking validation set user is not a unique user (i.e. it appears in training)

In [43]:
con.execute("""
    SELECT
        COUNT(DISTINCT g.user_id) AS evaluation_users,
        COUNT(DISTINCT u.user_id) AS mf_known_users
    FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet') AS g
    LEFT JOIN read_parquet('../data/processed/mf_users.parquet') AS u
        ON g.user_id = u.user_id
""").df()

   evaluation_users  mf_known_users
0           2203571         1146634

### Validation population
- Chose chronological 2022 validation.
- Defined relevance as rating >= 4.
- Included every user with at least one positive 2022 interaction when constructing ground truth.
- For MF evaluation, restricted the personalized evaluation population to users present in the pre-2022 MF user mapping.
- This excludes 1,056,937 validation users who represent user cold-start; user cold-start is outside the primary project scope.
- Item cold-start remains the primary evaluation dimension.

In [44]:
ground_truth_sample = con.execute("""
    SELECT
        g.user_id,
        g.item_id,
        g.item_cohort,
        i.mf_item_idx
    FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet') AS g
    LEFT JOIN read_parquet('../data/processed/mf_items.parquet') AS i
        ON g.item_id = i.parent_asin
    WHERE g.user_id IN (
        SELECT user_id
        FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet')
        LIMIT 32
    )
""").df()

ground_truth_sample.head()

                        user_id     item_id item_cohort  mf_item_idx
0  AHSDCNEXWSOF5JUWQXISNGAGPO2Q  B0BWD4WGJB        warm      1385687
1  AHY7HJLQWVSQS5LBIY2FHZ2BUW6Q  B08TRRCNQ9         low      1296460
2  AEWXPL7KOD4SWQBUDDIBMYRVWAOA  B09ZYDJQ2D        warm      1372418
3  AER3MHHJKLMNOE4KABISAGTZTPUA  B07PBLNJZ7        warm      1013860
4  AGMHXH5S4QV2N5LONC4XG7Y6TLUA  B0C3NMZ2C7        warm      1389649

In [45]:
con.register("eval_users_sample", eval_users)

In [46]:
ground_truth_sample = con.execute("""
    SELECT
        g.user_id,
        g.item_id,
        g.item_cohort,
        i.mf_item_idx
    FROM read_parquet('../data/processed/mf_validation_ground_truth.parquet') AS g
    LEFT JOIN read_parquet('../data/processed/mf_items.parquet') AS i
        ON g.item_id = i.parent_asin
    INNER JOIN eval_users_sample AS e
        ON g.user_id = e.user_id
""").df()

In [47]:
print("Ground-truth users:", ground_truth_sample["user_id"].nunique())
print("Evaluation users:", eval_users["user_id"].nunique())
print("Ground-truth positive pairs:", len(ground_truth_sample))
print("True-cold positives:", (ground_truth_sample["mf_item_idx"].isna()).sum())

Ground-truth users: 32
Evaluation users: 32
Ground-truth positive pairs: 56
True-cold positives: 13

In [48]:
import numpy as np

ground_truth_by_user = {
    user_id: set(group["mf_item_idx"].dropna().astype(int))
    for user_id, group in ground_truth_sample.groupby("user_id")
}

recall5_values = []
recall10_values = []

for row_idx, user_id in enumerate(eval_users["user_id"]):
    relevant_items = ground_truth_by_user[user_id]

    # Only MF-scoreable relevant items can possibly be retrieved.
    # True-cold items have no MF item index.
    if not relevant_items:
        continue

    recommended5 = set(top5_indices[row_idx].cpu().numpy())
    recommended10 = set(top10_indices[row_idx].cpu().numpy())

    recall5_values.append(
        len(recommended5 & relevant_items) / len(relevant_items)
    )

    recall10_values.append(
        len(recommended10 & relevant_items) / len(relevant_items)
    )

print("Recall@5:", np.mean(recall5_values))
print("Recall@10:", np.mean(recall10_values))

Recall@5: 0.0
Recall@10: 0.0

In [32]:
# Pick the first evaluation user
user_id = eval_users.iloc[0]["user_id"]

print("User:", user_id)

print("\nGround-truth items:")
print(
    ground_truth_sample[
        ground_truth_sample["user_id"] == user_id
    ][["item_id", "item_cohort", "mf_item_idx"]]
)

print("\nTop-10 MF item indices:")
print(top10_indices[0].cpu().numpy())

User: AHXG5OJ6YEFCM44FTZ22DJBNBP2A

Ground-truth items:
       item_id item_cohort  mf_item_idx
27  B0C5CKJQ2Y        warm      1390738
28  B08N38WQSH        warm      1269135

Top-10 MF item indices:
[1045884  465543  175846  555259  192966  875261  242302  510795 1179322
  843941]

In [33]:
user_ground_truth = set(
    ground_truth_sample[
        (ground_truth_sample["user_id"] == user_id)
        & (ground_truth_sample["mf_item_idx"].notna())
    ]["mf_item_idx"].astype(int)
)

user_recommendations = set(
    top10_indices[0].cpu().numpy()
)

print("MF-scoreable ground truth:", user_ground_truth)
print("Top-10:", user_recommendations)
print("Intersection:", user_ground_truth & user_recommendations)

MF-scoreable ground truth: {1390738, 1269135}
Top-10: {np.int64(843941), np.int64(192966), np.int64(175846), np.int64(465543), np.int64(510795), np.int64(1179322), np.int64(555259), np.int64(1045884), np.int64(875261), np.int64(242302)}
Intersection: set()

In [34]:
print("Score min:", scores[0].min().item())
print("Score max:", scores[0].max().item())
print("Top-10 scores:", top10_scores[0].cpu().numpy())

Score min: -19.919340133666992
Score max: 17.005224227905273
Top-10 scores: [17.005224  16.6255    16.252693  15.32283   15.297259  15.15778
 15.106215  14.942964  14.90984   14.8833275]

In [35]:
user_id = eval_users.iloc[0]["user_id"]

print("User:", user_id)

print("\nGround truth:")
print(
    ground_truth_sample[
        ground_truth_sample["user_id"] == user_id
    ][["item_id", "item_cohort", "mf_item_idx"]]
)

print("\nTop-10 MF indices:")
print(top10_indices[0].cpu().numpy())

User: AHXG5OJ6YEFCM44FTZ22DJBNBP2A

Ground truth:
       item_id item_cohort  mf_item_idx
27  B0C5CKJQ2Y        warm      1390738
28  B08N38WQSH        warm      1269135

Top-10 MF indices:
[1045884  465543  175846  555259  192966  875261  242302  510795 1179322
  843941]

In [36]:
user_ground_truth = set(
    ground_truth_sample[
        (ground_truth_sample["user_id"] == user_id)
        & (ground_truth_sample["mf_item_idx"].notna())
    ]["mf_item_idx"].astype(int)
)

user_recommendations = set(
    top10_indices[0].cpu().numpy()
)

print("\nMF-scoreable ground truth:", user_ground_truth)
print("Top-10:", user_recommendations)
print("Intersection:", user_ground_truth & user_recommendations)

MF-scoreable ground truth: {1390738, 1269135}
Top-10: {np.int64(843941), np.int64(192966), np.int64(175846), np.int64(465543), np.int64(510795), np.int64(1179322), np.int64(555259), np.int64(1045884), np.int64(875261), np.int64(242302)}
Intersection: set()

In [37]:
relevant_idx = 1381682

relevant_score = scores[0, relevant_idx].item()
top_score = scores[0, top10_indices[0, 0]].item()

print("Relevant item score:", relevant_score)
print("Top recommendation score:", top_score)
print(
    "Relevant item rank:",
    int((scores[0] > relevant_score).sum().item()) + 1
)

Relevant item score: -2.257059335708618
Top recommendation score: 17.005224227905273
Relevant item rank: 911219

In [38]:
with torch.no_grad():
    user_norms = torch.linalg.vector_norm(
        model.user_embeddings.weight,
        dim=1,
    )

    item_norms = torch.linalg.vector_norm(
        model.item_embeddings.weight,
        dim=1,
    )

print("User embedding norm:")
print("  mean:", user_norms.mean().item())
print("  median:", user_norms.median().item())
print("  max:", user_norms.max().item())

print("\nItem embedding norm:")
print("  mean:", item_norms.mean().item())
print("  median:", item_norms.median().item())
print("  max:", item_norms.max().item())

User embedding norm:
  mean: 3.9369823932647705
  median: 3.9153635501861572
  max: 7.9875030517578125

Item embedding norm:
  mean: 3.93179988861084
  median: 3.9110143184661865
  max: 7.623149394989014

### Debugging

In [49]:
test_user_id = eval_users.iloc[0]["user_id"]
test_user_idx = int(eval_users.iloc[0]["user_idx"])

known_item = con.execute("""
    SELECT
        i.mf_item_idx,
        r.parent_asin,
        r.rating
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet') AS r
    INNER JOIN read_parquet('../data/processed/mf_items.parquet') AS i
        ON r.parent_asin = i.parent_asin
    WHERE r.user_id = ?
      AND r.timestamp < 1640995200000
    LIMIT 1
""", [test_user_id]).df()

known_item

   mf_item_idx parent_asin  rating
0       232360  B0062P7ISY     1.0

In [50]:
test_item_idx = int(known_item.iloc[0]["mf_item_idx"])

item_score = scores[0, test_item_idx].item()

rank = int(
    (scores[0] > scores[0, test_item_idx]).sum().item()
) + 1

print("User:", test_user_id)
print("Training item:", known_item.iloc[0]["parent_asin"])
print("Rating:", known_item.iloc[0]["rating"])
print("MF item index:", test_item_idx)
print("Score:", item_score)
print("Rank:", rank)

User: AHXG5OJ6YEFCM44FTZ22DJBNBP2A
Training item: B0062P7ISY
Rating: 1.0
MF item index: 232360
Score: -inf
Rank: 1395100

### Attempt 2: Evaluation

In [51]:
raw_user_scores = (
    user_vectors[0] @ item_vectors.T
    + user_biases[0]
    + item_biases
    + model.global_bias
)

test_item_idx = int(known_item.iloc[0]["mf_item_idx"])

item_score = raw_user_scores[test_item_idx].item()

rank = int(
    (raw_user_scores > raw_user_scores[test_item_idx]).sum().item()
) + 1

print("User:", test_user_id)
print("Training item:", known_item.iloc[0]["parent_asin"])
print("Rating:", known_item.iloc[0]["rating"])
print("MF item index:", test_item_idx)
print("Raw score:", item_score)
print("Raw rank:", rank)
print("Raw max score:", raw_user_scores.max().item())

User: AHXG5OJ6YEFCM44FTZ22DJBNBP2A
Training item: B0062P7ISY
Rating: 1.0
MF item index: 232360
Raw score: -0.39830881357192993
Raw rank: 626279
Raw max score: 17.005226135253906

In [52]:
high_rating_item = con.execute("""
    SELECT
        i.mf_item_idx,
        r.parent_asin,
        r.rating
    FROM read_parquet('../data/processed/electronics_interactions/*.parquet') AS r
    INNER JOIN read_parquet('../data/processed/mf_items.parquet') AS i
        ON r.parent_asin = i.parent_asin
    WHERE r.user_id = ?
      AND r.timestamp < 1640995200000
      AND r.rating = 5
    LIMIT 1
""", [test_user_id]).df()

high_rating_item

   mf_item_idx parent_asin  rating
0       283167  B008TSVZHM     5.0

In [53]:
high_item_idx = int(high_rating_item.iloc[0]["mf_item_idx"])

high_score = raw_user_scores[high_item_idx].item()

high_rank = int(
    (raw_user_scores > raw_user_scores[high_item_idx]).sum().item()
) + 1

print("User:", test_user_id)
print("Training item:", high_rating_item.iloc[0]["parent_asin"])
print("Rating:", high_rating_item.iloc[0]["rating"])
print("MF item index:", high_item_idx)
print("Raw score:", high_score)
print("Raw rank:", high_rank)

User: AHXG5OJ6YEFCM44FTZ22DJBNBP2A
Training item: B008TSVZHM
Rating: 5.0
MF item index: 283167
Raw score: 1.6068944931030273
Raw rank: 341799

In [56]:
gt_schema = con.execute("""
    DESCRIBE
    SELECT *
    FROM read_parquet(
        '../data/processed/mf_validation_ground_truth.parquet'
    )
""").df()

gt_schema

   column_name column_type null   key default extra
0      user_id     VARCHAR  YES  None    None  None
1      item_id     VARCHAR  YES  None    None  None
2  item_cohort     VARCHAR  YES  None    None  None

In [57]:
con.execute("""
    SELECT *
    FROM read_parquet(
        '../data/processed/mf_validation_ground_truth.parquet'
    )
    LIMIT 5
""").df()

                        user_id     item_id item_cohort
0  AHSDCNEXWSOF5JUWQXISNGAGPO2Q  B0BWD4WGJB        warm
1  AHY7HJLQWVSQS5LBIY2FHZ2BUW6Q  B08TRRCNQ9         low
2  AEWXPL7KOD4SWQBUDDIBMYRVWAOA  B09ZYDJQ2D        warm
3  AER3MHHJKLMNOE4KABISAGTZTPUA  B07PBLNJZ7        warm
4  AGMHXH5S4QV2N5LONC4XG7Y6TLUA  B0C3NMZ2C7        warm

In [58]:
validation_positive = con.execute("""
    SELECT
        g.user_id,
        g.item_id,
        g.item_cohort,
        i.mf_item_idx
    FROM read_parquet(
        '../data/processed/mf_validation_ground_truth.parquet'
    ) AS g
    LEFT JOIN read_parquet(
        '../data/processed/mf_items.parquet'
    ) AS i
        ON g.item_id = i.parent_asin
    WHERE g.user_id = ?
      AND g.item_cohort = 'warm'
    LIMIT 1
""", [test_user_id]).df()

validation_positive

                        user_id     item_id item_cohort  mf_item_idx
0  AHXG5OJ6YEFCM44FTZ22DJBNBP2A  B08N38WQSH        warm      1269135

In [59]:
validation_item_idx = int(
    validation_positive.iloc[0]["mf_item_idx"]
)

validation_score = raw_user_scores[validation_item_idx].item()

validation_rank = int(
    (raw_user_scores > raw_user_scores[validation_item_idx]).sum().item()
) + 1

print("Validation item:",
      validation_positive.iloc[0]["item_id"])
print("Cohort:",
      validation_positive.iloc[0]["item_cohort"])
print("MF item index:", validation_item_idx)
print("Raw score:", validation_score)
print("Raw rank:", validation_rank)

Validation item: B08N38WQSH
Cohort: warm
MF item index: 1269135
Raw score: -6.199119567871094
Raw rank: 1301720